@host = http://127.0.0.1:8000
@api_key = DYXcU3AshPCpUC0PzM1BMDnUbcoroGZm
@api_key_2 = ZK5YxQaXKMzGJL7QkdwMJjaaN35o2YlD
@test_id = 1

### unauthorized check
GET {{host}}/api/v1/clients/

### api_key access check
GET {{host}}/api/v1/clients/
Authorization: Bearer {{api_key_2}}

### Get all clients BEETJE BROKEN TRAAG
GET {{host}}/api/v1/clients/
Authorization: Bearer {{api_key}}

### Get specific client
GET {{host}}/api/v1/clients/{{test_id}}/
Authorization: Bearer {{api_key}}

### Post new client
POST {{host}}/api/v1/clients/
Authorization: Bearer {{api_key}}
Content-Type: application/json

{
    "name": "Nieuwe Klant",
    "address": "1234 Nieuwe Straat",
    "city": "Amsterdam",
    "zip_code": "1234AB",
    "province": "Noord-Holland",
    "country": "Nederland",
    "contact_name": "Jan Janssen",
    "contact_phone": "06-12345678",
    "contact_email": "nieuwe.klant@example.com"
}

### put new information in clients
PUT {{host}}/api/v1/clients/{{test_id}}/
Authorization: Bearer {{api_key}}
Content-Type: application/json

{
  "name": "Updated Client Name",
  "address": "789 Updated Street",
  "city": "Updated City",
  "zip_code": "99999",
  "province": "Updated Province",
  "country": "United States",
  "contact_name": "Updated Contact Name",
  "contact_phone": "555-999-8888",
  "contact_email": "updated.contact@example.com",
  "updated_at": "2024-09-30T14:21:34.248255Z"
}

### Delete Client
DELETE {{host}}/api/v1/clients/{{test_id}}/
Authorization: Bearer {{api_key}}

### get orders for client(client_id)
GET {{host}}/api/v1/clients/{{test_id}}/orders/
