@host = http://127.0.0.1:8000
@api_key = a1b2c3d4e5
@test_id = 1

### Get all inventories
GET {{host}}/api/v1/inventories/
Authorization: Bearer {{api_key}}

### Get specific inventory
GET {{host}}/api/v1/inventories/{{test_id}}/
Authorization: Bearer {{api_key}}

### Post new inventory
POST {{host}}/api/v1/inventories/
Authorization: Bearer {{api_key}}
Content-Type: application/json

{
    "item_id": "P000001",
    "description": "New inventory item",
    "item_reference": "new-ref",
    "locations": [12345, 67890],
    "total_on_hand": 100,
    "total_expected": 50,
    "total_ordered": 20,
    "total_allocated": 10,
    "total_available": 90
}

### Put update inventory
PUT {{host}}/api/v1/inventories/{{test_id}}/
Authorization: Bearer {{api_key}}
Content-Type: application/json

{
    "item_id": "P990002",
    "description": "Updated inventory item",
    "item_reference": "updated-ref",
    "locations": [12345, 67890],
    "total_on_hand": 150,
    "total_expected": 60,
    "total_ordered": 30,
    "total_allocated": 20,
    "total_available": 110
}

### Delete inventory
DELETE {{host}}/api/v1/inventories/{{test_id}}/
Authorization: Bearer {{api_key}}