@host = http://127.0.0.1:8000
@api_key = DYXcU3AshPCpUC0PzM1BMDnUbcoroGZm
@test_id = P000001

### Get all items
GET {{host}}/api/v1/items/
Authorization: Bearer {{api_key}}

### Get specific item
GET {{host}}/api/v1/items/{{test_id}}/
Authorization: Bearer {{api_key}}

### Post new item
POST {{host}}/api/v1/items/
Authorization: Bearer {{api_key}}
Content-Type: application/json

{
    "uid": "P000001",
    "code": "ITEM001",
    "description": "Item Description",
    "short_description": "Short Description",
    "upc_code": "123456789012",
    "model_number": "MODEL001",
    "commodity_code": "COM001",
    "item_line": 1,
    "item_group": 1,
    "item_type": 1,
    "unit_purchase_quantity": 10,
    "unit_order_quantity": 5,
    "pack_order_quantity": 2,
    "supplier_id": 1,
    "supplier_code": 1001,
    "supplier_part_number": 2001
}

### Put update item
PUT {{host}}/api/v1/items/{{test_id}}/
Authorization: Bearer {{api_key}}
Content-Type: application/json

{
    "uid": "P000001",
    "code": "UPDATED-ITEM001",
    "description": "Updated Item Description",
    "short_description": "Updated Short Description",
    "upc_code": "123456789012",
    "model_number": "MODEL001",
    "commodity_code": "COM001",
    "item_line": 1,
    "item_group": 1,
    "item_type": 1,
    "unit_purchase_quantity": 10,
    "unit_order_quantity": 5,
    "pack_order_quantity": 2,
    "supplier_id": 1,
    "supplier_code": 1001,
    "supplier_part_number": 2001
}

### Delete item
DELETE {{host}}/api/v1/items/{{test_id}}/
Authorization: Bearer {{api_key}}