@host = http://localhost:3000
@api_key = a1b2c3d4e5

### Get all item types
GET {{host}}/api/v1/item_types
API_KEY: {{api_key}}

### Get specific item type
GET {{host}}/api/v1/item_types/2
API_KEY: {{api_key}}

### Get all items of specific item type
GET {{host}}/api/v1/item_types/2/items
API_KEY: {{api_key}}