@host = http://127.0.0.1:8000
@api_key = ZK5YxQaXKMzGJL7QkdwMJjaaN35o2YlD
@test_id = 9999999999

### Get all item groups
GET {{host}}/api/v1/item_groups/
Authorization: Bearer {{api_key}}

### Get specific item group
GET {{host}}/api/v1/item_groups/{{test_id}}/
Authorization: Bearer {{api_key}}

### Put update item group
PUT {{host}}/api/v1/item_groups/{{test_id}}/
Authorization: Bearer {{api_key}}
Content-Type: application/json

{
    "id": {{test_id}},
    "name": "Updated Electronics",
    "description": "Updated group for electronic items"
}

### Post new item group
POST {{host}}/api/v1/item_groups/
Authorization: Bearer {{api_key}}
Content-Type: application/json

{
    "id": {{test_id}},
    "name": "Electronics",
    "description": "Group for electronic items"
}

### Delete item group
DELETE {{host}}/api/v1/item_groups/{{test_id}}/
Authorization: Bearer {{api_key}}
