@host = http://127.0.0.1:8000
@api_key = DYXcU3AshPCpUC0PzM1BMDnUbcoroGZm
@test_id = 1

### Get all item lines
GET {{host}}/api/v1/item_lines/
Authorization: Bearer {{api_key}}

### Get specific item line
GET {{host}}/api/v1/item_lines/{{test_id}}/
Authorization: Bearer {{api_key}}

### Post new item line
POST {{host}}/api/v1/item_lines/
Authorization: Bearer {{api_key}}
Content-Type: application/json

{
    "name": "New Item Line",
    "description": "New line description"
}

### Put update item line
PUT {{host}}/api/v1/item_lines/{{test_id}}/
Authorization: Bearer {{api_key}}
Content-Type: application/json

{
    "name": "Updated Item Line",
    "description": "Updated description"
}

### Delete item line
DELETE {{host}}/api/v1/item_lines/{{test_id}}/
Authorization: Bearer {{api_key}}

### get items for item line(item_line_id)
GET {{host}}/api/v1/item_lines/{{test_id}}/items/