# @host = http://localhost:8080
@host = http://127.0.0.1:8000
@api_key = a1b2c3d4e5
@test_id = 9999999999

### Get all locations
GET {{host}}/api/v1/locations/
Authorization: Bearer {{api_key}}

### Get specific location
GET {{host}}/api/v1/locations/{{test_id}}/
Authorization: Bearer {{api_key}}

### Put update location
PUT {{host}}/api/v1/locations/{{test_id}}/
Authorization: Bearer {{api_key}}
Content-Type: application/json

{
    "id": {{test_id}},
    "warehouse_id": 1,
    "code": "UPDATED-A.1.1",
    "name": "Updated Row: A, Rack: 1, Shelf: 1"
}

### Post new location
POST {{host}}/api/v1/locations/
Authorization: Bearer {{api_key}}
Content-Type: application/json

{
    "warehouse_id": 1,
    "code": "A.1.1",
    "name": "Row: A, Rack: 1, Shelf: 1"
}

### Delete location
DELETE {{host}}/api/v1/locations/{{test_id}}/
Authorization: Bearer {{api_key}}