@host = http://localhost:3000
@api_key = a1b2c3d4e5

### Get All Orders
GET {{host}}/api/v1/orders
Authorization: Bearer {{api_key}}

### Get Specific Order
GET {{host}}/api/v1/orders/123
Authorization: Bearer {{api_key}}

### Create a New Order
POST {{host}}/api/v1/orders
Authorization: Bearer {{api_key}}
Content-Type: application/json

{
    "shipment_id": 1,
    "ship_to": 2,
    "bill_to": 3
}

### Update an Order
PUT {{host}}/api/v1/orders/123
Authorization: Bearer {{api_key}}
Content-Type: application/json

{
    "shipment_id": 2,
    "ship_to": 4,
    "bill_to": 5
}

### Delete an Order
DELETE {{host}}/api/v1/orders/123
Authorization: Bearer {{api_key}}
