# @host = http://localhost:8080
@host = http://127.0.0.1:8000
@api_key = DYXcU3AshPCpUC0PzM1BMDnUbcoroGZm
@test_id = 1

### Get Warehouses
GET {{host}}/api/v1/warehouses/
Authorization: Bearer {{api_key}}

### Get specific warehouse
GET {{host}}/api/v1/warehouses/{{test_id}}/
Authorization: Bearer {{api_key}}

### Add a new warehouse
POST {{host}}/api/v1/warehouses/
Content-Type: application/json
Authorization: Bearer {{api_key}}

{
    "code": "YQZZNL56",
    "name": "Heemskerk cargo hub",
    "address": "Karlijndreef 281",
    "province": "WH",
    "country": "Netherlands"
}

### Put update warehouse
PUT {{host}}/api/v1/warehouses/{{test_id}}/
Authorization: Bearer {{api_key}}
Content-Type: application/json

{
    "name": "Updated Warehouse",
    "address": "456 Updated St",
    "city": "Updated City",
    "province": "UP",
    "country": "Netherlands"
}

### Delete warehouse
DELETE {{host}}/api/v1/warehouses/{{test_id}}/
Authorization: Bearer {{api_key}}
