name: Django CI

on:
  push:
    branches: [ "New-main" ]
  pull_request:
    branches: [ "New-main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   max-parallel: 4
    #   matrix:
    #     python-version: [3.9]

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    # strategy:
    #   matrix:
    #     python-version: [3.9]
    steps:
    # - name: Check out repository
    #   uses: actions/checkout@v4

    # - name: Set up Python 3.9
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run endpoint tests
      run: pytest endpoints_tests.py --junitxml=results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: endpoints-test-results
        path: results.xml
