name: Django CI

on:
  push:
    branches: [ "New-main" ]
  pull_request:
    branches: [ "New-main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./groep6---INFSCP01---2425
      - name: Test with pytest
        run: |
          pytest
        working-directory: ./groep6---INFSCP01---2425
      

  upload:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: endpoints-test-results
        path: results.xml

