name: Integratietests

on:
  push:
    branches: [ "New-main" ]

jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run integration tests
        run: |
          pytest
      - name: Generate test report
        run: |
          pytest --html=report.html
