name: Integratietests

on:
  push:
    branches: [ "New-main" ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Start API server
        run: |
          nohup python3 main.py --port 3000 &
          sleep 5  # Wait for the server to start

      - name: Run integration tests
        run: |
          pytest endpoints_tests.py

      - name: Generate test report
        run: |
          pytest --html=report.html

      - name: Deploy to live server
        if: success()  # This step runs only if the previous steps were successful
        run: |
          ssh user@live-server "cd api\main.py && git pull origin New-main && systemctl restart your_service"  # Replace with your actual deployment command